services:
  # =======================================================================
  # INFRASTRUCTURE TIER
  # =======================================================================
  postgres-db:
    image: postgres:16-alpine
    container_name: fa_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-faadmin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-fadb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
    # This tells Docker how to test if the database inside is actually ready for traffic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-faadmin} -d ${POSTGRES_DB:-fadb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
     - finance_network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: fa_rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - finance_network

  redis:
    image: redis:7.2-alpine
    container_name: fa_redis
    restart: unless-stopped
    ports:
      - "5207:6379" # Maps your appsettings port 5207 straight to internal 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - finance_network

  # =======================================================================
  # APPLICATION SERVICES TIER (.NET 10 Microservices)
  # =======================================================================
  identity-service:
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    container_name: fa_identity
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5205 # Binds to internal container port 5205
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=${POSTGRES_DB:-fadb};Username=${POSTGRES_USER:-faadmin};Password=${POSTGRES_PASSWORD};SearchPath=identity_schema
      - JwtSettings__Key=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER:-IdentityService}
      - JwtSettings__Audience=${JWT_AUDIENCE:-FinanceAggregatorClients}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
    # UPDATED: Enforces that postgres-db must pass its health check first
    depends_on:
      rabbitmq:
        condition: service_started
      postgres-db:
        condition: service_healthy
    networks:
      - finance_network

  wallet-service:
    build:
      context: .
      dockerfile: src/WalletService/Dockerfile
    container_name: fa_wallet
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5202 # Binds to internal container port 5202
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=${POSTGRES_DB:-fadb};Username=${POSTGRES_USER:-faadmin};Password=${POSTGRES_PASSWORD};SearchPath=wallet_schema
      - ConnectionStrings__Redis=${REDIS_PORT}
      - JwtSettings__Key=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER:-IdentityService}
      - JwtSettings__Audience=${JWT_AUDIENCE:-FinanceAggregatorClients}
      - Redis__Host=redis
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - HttpClientBaseAdress=${WALLET_SVC_HTTP_CLIENT_BASE_ADDR:-localhost}
    # UPDATED: Enforces that postgres-db must pass its health check first
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      postgres-db:
        condition: service_healthy
    networks:
      - finance_network

  yarp-gateway:
    build:
      context: .
      dockerfile: src/YarpGateway/Dockerfile
    container_name: fa_gateway
    restart: unless-stopped
    ports:
      - "5153:5153" # EXPOSED: Maps host port 5153 straight to container internal port 5153 for frontend (React)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5153 # App listens on port 5153 inside the container
      - JwtSettings__Key=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER:-IdentityService}
      - JwtSettings__Audience=${JWT_AUDIENCE:-FinanceAggregatorClients}
      ####
      - ReverseProxy__Routes__identityRoute__ClusterId=identityCluster
      - ReverseProxy__Routes__identityRoute__Match__Path=/api/v1/auth/{**remainder}
      - ReverseProxy__Routes__identityRoute__Transforms__0__PathPattern=api/v1/auth/{**remainder}
      - ReverseProxy__Routes__identityRoute__Transforms__1__RequestHeader=X-Gateway-Enforced
      - ReverseProxy__Routes__identityRoute__Transforms__1__Set=true
      ####
      - ReverseProxy__Routes__walletRoute__ClusterId=walletCluster
      - ReverseProxy__Routes__walletRoute__AuthorizationPolicy=Default
      - ReverseProxy__Routes__walletRoute__Match__Path=/api/v1/wallets/{**remainder}
      - ReverseProxy__Routes__walletRoute__Transforms__0__PathPattern=api/v1/wallets/{**remainder}
      ####
      - ReverseProxy__Routes__walletHubRoute__ClusterId=walletCluster
      - ReverseProxy__Routes__walletHubRoute__CorsPolicy=FrontendPolicy
      - ReverseProxy__Routes__walletHubRoute__Match__Path=/hubs/wallets/{**remainder}
      - ReverseProxy__Routes__walletHubRoute__Transforms__0__PathPattern=hubs/wallets/{**remainder}
      ####
      # - ReverseProxy__Clusters__identityCluster__Destinations__destination1__Address=http://localhost:5205
      # - ReverseProxy__Clusters__walletCluster__Destinations__destination1__Address=http://localhost:5202

    command: >
      dotnet YarpGateway.dll 
      --ReverseProxy:Clusters:identityCluster:Destinations:destination1:Address=http://identity-service:5205
      --ReverseProxy:Clusters:walletCluster:Destinations:destination1:Address=http://wallet-service:5202
    depends_on:
      - identity-service
      - wallet-service
    networks:
      - finance_network
    
  # =======================================================================
  # ASYNCHRONOUS NOTIFICATION WORKER SERVICE
  # =======================================================================
  notification-service:
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    container_name: fa_notification
    restart: unless-stopped
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER:-guest}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD:-guest}
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - finance_network

  # =======================================================================
  # FRONTEND USER PORTAL CLIENT
  # =======================================================================
  frontend-web:
    build:
      context: ./src/FinanceAggregator.Web
      dockerfile: Dockerfile
    container_name: fa_frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Maps local host port 3000 cleanly to internal Nginx container port 80
    depends_on:
      - yarp-gateway # Guarantees routing definitions and auth pipes are active before UI renders
    networks:
      - finance_network    

# =======================================================================
# PERSISTENT DATA TIERS & LOGICAL ISOLATION BRIDGES
# =======================================================================
volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  postgres_master_data:

networks:
  finance_network:
    driver: bridge